name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Atau nama branch utama Anda, misalnya master/main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Variabel rahasia GitHub
        password: ${{ secrets.DOCKER_PASSWORD }} # Variabel rahasia GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: . # Direktori tempat Dockerfile berada
        file: ./Dockerfile # Lokasi Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/uas-asj-coffeeshop:latest # Sesuaikan nama image Docker Hub Anda

    # Opsional: Jika Anda ingin juga menjalankan tes atau deploy di sini
    # - name: Run tests (jika ada)
    #   run: |
    #     docker compose up --build -d
    #     docker compose exec web python -m pytest # Contoh jika Anda punya tes
